language: ruby
bundler_args: --without guard
rvm:
  - "2.0"
  - "2.1"
  - ruby-head
script: "bundle exec rspec"
addons:
  code_climate:
    repo_token: 68f28e1d037ca7b58d24f943b59d82cd649e1f9b9f79437d4a5d864140dd4eb0
branches:
  only: master
notifications:
  email: false
